# Generated by Django 5.1 on 2024-08-26 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='count',
        ),
        migrations.AddField(
            model_name='order',
            name='count',
            field=models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
