# Generated by Django 5.1 on 2024-08-26 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_basket_count_order_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.basket'),
        ),
    ]
