# Generated by Django 5.1 on 2024-08-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_order_order_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_item',
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, default='noname', max_length=30),
        ),
    ]
